spring.datasource.url=jdbc:postgresql://localhost:5432/missionsJava
spring.datasource.username=postgres
spring.datasource.password=delya
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8082
